### ISSUE TITLE
.form-signin and resources 2.3.2

### ISSUE THREAD

**Issue by ccfontes** [weavejester/hiccup-bootstrap#6]
`[ccfontes/hiccup-bootstrap "0.1.3"]` fork was downloaded 2629 times.
`[hiccup-bootstrap "0.1.2"]` upstream was downloaded 108 times.

I suspect the reason is because I included a custom styles.css in my own jar, for a personal just works experience, which includes definition for class `.form-signin`. Since many developers use this class that is defined inline in the twitter bootstrap examples, they will prefer the fork version because it just works for their situation. Sure, this is just speculation.
That being said, what do you think about including the `styles.css`, or under another name?

styles.css

``` css
.form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
}

.form-signin .form-signin-heading,
.form-signin .checkbox {
        margin-bottom: 10px;
}

.form-signin input[type="text"],
.form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
}
```

I have prepared a version with 2.3.2 resources, so I would include them too for the merge request.
